# -*- coding: utf-8 -*-
"""Jupiter Ai labs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHY_wkVriWueGCZEwURagRjIr6Dj2UCF
"""

pip install dateparser

import datetime
import json
import re
import dateparser

def fetch_flights(origin: str, destination: str, date: str, min_price=None, max_price=None, max_stops=None):
    # Mock flight data
    mock_flights = [
        {"flight_number": "AI203", "airline": "Air India", "price": 4500, "departure_time": "06:00", "arrival_time": "08:05", "stops": 0},
        {"flight_number": "6E101", "airline": "IndiGo", "price": 5100, "departure_time": "07:30", "arrival_time": "08:45", "stops": 0},
        {"flight_number": "UK304", "airline": "Vistara", "price": 4800, "departure_time": "09:00", "arrival_time": "11:30", "stops": 1},
        {"flight_number": "AI450", "airline": "Air India", "price": 7000, "departure_time": "10:00", "arrival_time": "12:30", "stops": 1},
        {"flight_number": "6E202", "airline": "IndiGo", "price": 5500, "departure_time": "11:00", "arrival_time": "13:30", "stops": 0}
    ]

    # Apply price and stop filters if provided
    filtered_flights = [
        flight for flight in mock_flights
        if (min_price is None or flight["price"] >= min_price) and
           (max_price is None or flight["price"] <= max_price) and
           (max_stops is None or flight["stops"] <= max_stops)
    ]

    # Calculate duration for each filtered flight
    for flight in filtered_flights:
        dep = datetime.datetime.strptime(flight["departure_time"], "%H:%M")
        arr = datetime.datetime.strptime(flight["arrival_time"], "%H:%M")
        if arr < dep:
            arr += datetime.timedelta(days=1)
        flight["duration_minutes"] = int((arr - dep).total_seconds() / 60)

    # Find the cheapest and fastest flights
    cheapest = min(filtered_flights, key=lambda x: x['price']) if filtered_flights else None
    fastest = min(filtered_flights, key=lambda x: x['duration_minutes']) if filtered_flights else None

    # Format price with "Rs." instead of ₹
    if cheapest:
        cheapest["price"] = f"Rs. {cheapest['price']:,.0f}"
    if fastest:
        fastest["price"] = f"Rs. {fastest['price']:,.0f}"

    return {
        "origin": origin.title(),
        "destination": destination.title(),
        "date": date,
        "date_readable": datetime.datetime.strptime(date, "%Y-%m-%d").strftime("%A, %B %d, %Y"),
        "cheapest_flight": cheapest,
        "fastest_flight": fastest,
        "total_flights": len(filtered_flights),
        "filters_applied": {
            "min_price": min_price,
            "max_price": max_price,
            "max_stops": max_stops
        },
        "all_flights": filtered_flights,
        "status": "Flights fetched successfully"
    }

def parse_user_input(user_input: str):
    # Extract origin and destination cities
    match = re.search(r'from\s+([\w\s]+?)\s+to\s+([\w\s]+?)(\s+|$)', user_input, re.IGNORECASE)
    if not match:
        print("❌ Could not extract origin and destination. Please use the format: 'from <city> to <city>'")
        return None, None, None, None, None, None

    origin = match.group(1).strip()
    destination = match.group(2).strip()

    if origin.lower() == destination.lower():
        print("⚠️ Origin and destination cannot be the same.")
        return None, None, None, None, None, None

    # Extract date from user input
    date_match = re.search(r'(?:on|for)\s+(.+)', user_input, re.IGNORECASE)
    date_text = date_match.group(1).strip() if date_match else None

    # If no date found, assume today and notify user
    if not date_text:
        print("⚠️ No date provided, assuming today's date.")
        parsed_date = datetime.date.today()
    else:
        parsed_date = dateparser.parse(date_text, settings={'PREFER_DATES_FROM': 'future'})
        if not parsed_date:
            print("⚠️ Could not parse date. Defaulting to today.")
            parsed_date = datetime.date.today()
        elif parsed_date.date() < datetime.date.today():
            print("⚠️ Travel date cannot be in the past.")
            return None, None, None, None, None, None

    travel_date = parsed_date.strftime("%Y-%m-%d")

    # Extract price range and stop preferences
    min_price, max_price, max_stops = None, None, None
    price_match = re.search(r'price\s+(\d+)\s+to\s+(\d+)', user_input, re.IGNORECASE)
    if price_match:
        min_price = int(price_match.group(1))
        max_price = int(price_match.group(2))

    stops_match = re.search(r'(\d+)\s+stops?', user_input, re.IGNORECASE)
    if stops_match:
        max_stops = int(stops_match.group(1))

    return origin, destination, travel_date, min_price, max_price, max_stops

def display_flight_summary(result):
    print(f"\n📍 Route: {result['origin']} ➡️ {result['destination']} on {result['date_readable']}")

    # Display cheapest flight
    if result['cheapest_flight']:
        print(f"✈️ Cheapest: {result['cheapest_flight']['flight_number']} ({result['cheapest_flight']['airline']}) - {result['cheapest_flight']['price']}")
    else:
        print("✈️ No flights found matching the criteria.")

    # Display fastest flight
    if result['fastest_flight']:
        print(f"⚡ Fastest: {result['fastest_flight']['flight_number']} - {result['fastest_flight']['duration_minutes']} mins")
    else:
        print("⚡ No flights found matching the criteria.")

    # Display all flights
    if not result['all_flights']:
        print("⚠️ No flights found for your criteria.")

    print("\n📦 AIgent JSON Response:\n")
    print(json.dumps(result, indent=4))

def run_agent_simulation():
    print("👋 Welcome to FlightBookingAssistant (Simulated AIgent)")
    print("💬 Try queries like:")
    print("  ➤ Book a flight from Delhi to Mumbai on Friday")
    print("  ➤ I want to fly from Bangalore to Hyderabad for tomorrow")
    print("  ➤ Find flights from Delhi to Mumbai with price between 4500 to 5500 and 0 stops\n")

    while True:
        user_input = input("🗣️  Your travel query: ")

        # Parse the user input and fetch flights
        origin, destination, travel_date, min_price, max_price, max_stops = parse_user_input(user_input)

        if origin and destination:
            result = fetch_flights(origin, destination, travel_date, min_price, max_price, max_stops)
            display_flight_summary(result)
        else:
            print("❌ Please use a valid query like: 'Book a flight from <city> to <city> on <date>'")

        cont = input("\n🔁 Search another flight? (y/n): ").strip().lower()
        if cont != 'y':
            print("👋 Goodbye! Safe travels!")
            break

if __name__ == "__main__":
    run_agent_simulation()

#            Book a flight from Delhi to Mumbai on Saturday
#            Find flights from Delhi to Mumbai with price between 4500 to 5500 and 0 stops
#            I want to fly from Bangalore to Hyderabad